image: maven:3.9.6-eclipse-temurin-21

services:
  - name: postgres:15
    alias: db

variables:
  SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
  SPRING_DATASOURCE_USERNAME: myuser
  SPRING_DATASOURCE_PASSWORD: mypass
  POSTGRES_DB: mydb
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypass

cache:
  paths:
    - .m2/repository

stages:
  - test
  - build

test:
  stage: test
  script:
    - mvn test

build:
  stage: build
  script:
    - mvn package -DskipTests
