image: jelastic/maven:3.9.5-openjdk-21

cache:
  paths:
    - .m2/repository

stages:
  - test
  - build

mytest:
  stage: test
  script:
    - 'mvn test'
  except:
    - main
mybuild:
  stage: build
  script:
    - mvn package -DskipTests
  only:
    - main
